name: 'jaffle_shop_metrics'

config-version: 2
version: '0.1'

profile: 'jaffle_shop_metrics'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  jaffle_shop_metrics:
      materialized: table
      staging:
        materialized: view


models:
  anyvan_analytics_dwh:
    adhoc:
      +materialized: view
      +tags: 'adhoc'

    DWH: 
      Data_Source_Views:
        +materialized: table
        +tags: "data_source"
        +schema: tableau_data_sources

      Dim_stage:
        +materialized: table
        +tags: 
          - "dimension"
          - "stage"
        +schema: staging

      Dimensions:
        +materialized: table #some are incremenetal in config block, which will override this materialization definition.
        +tags:
          - "dimension"

      fact_stage:
        +materialized: table
        +tags: 
          - "fact"
          - "stage"
        +schema: staging

      Facts:
        +materialized: table
        +tags: 
          - "fact"

      System:
        +materialized: view
        +tags: "system"

    v5_mmr_boards:
      +materialized: 'table'
      +schema: 'DWH'
      +enabled: false

    # disable both pinterest models if not using pinterest ads
    pinterest:
      enabled: false
    pinterest_source:
      enabled: false

    # disable both microsoft ads models if not using microsoft ads
    microsoft_ads:
      enabled: false
    microsoft_ads_source:
      enabled: false

    # disable both linkedin ads models if not using linkedin ads
    linkedin:
      enabled: false
    linkedin_source:
      enabled: false

    # disable both twitter ads models if not using twitter ads
    twitter_ads:
      enabled: false
    twitter_ads_source:
      enabled: false

    # disable all three facebook ads models if not using facebook ads
    facebook_ads:
      enabled: false #IF YOU ARE USING FACEBOOK, DELETE THIS CONFIG, DO NOT SIMPLY SET TO TRUE
    facebook_ads_source:
      enabled: false #IF YOU ARE USING FACEBOOK, DELETE THIS CONFIG, DO NOT SIMPLY SET TO TRUE
    facebook_ads_creative_history:
      enabled: false #IF YOU ARE USING FACEBOOK, DELETE THIS CONFIG, DO NOT SIMPLY SET TO TRUE

    # disable both snapchat ads models if not using snapchat ads
    snapchat_ads:
      enabled: false
    snapchat_ads_source:
      enabled: false

    # disable both tiktok ads models if not using tiktok ads
    tiktok_ads:
      enabled: false
    tiktok_ads_source:
      enabled: false